// AUTO-GENERATED by website/scripts/gen-ui-index.mjs from the dashboard source — DO NOT EDIT.
// Regenerate with `npm run gen:ui`; the same plans as `guide_plan` in src/kiro_crew/docs/ui-index.generated.json.
import type { UiGuidePlan } from './types'

/** The `build_digest` of the packaged index this bundle was built with (see `guideBuildDigest`). */
export const GUIDE_BUILD_DIGEST = "sha256:51f5e44bb21947881c5ce290ff34bac88ac942970253755bd7973faa71cc064b"

/** Curated location ids: the only ids a live observation may name. */
export const GUIDE_OBSERVABLE_IDS: readonly string[] = [
  "agents.add",
  "agents.chat",
  "agents.create-first",
  "agents.delete",
  "agents.edit-avatar",
  "agents.manage-memory",
  "apps.detail.disable",
  "apps.detail.install",
  "apps.detail.sync",
  "apps.detail.uninstall",
  "apps.detail.update",
  "apps.library.tile-details",
  "apps.refresh-store",
  "apps.sources",
  "apps.sources.add-registry",
  "artifacts.add-menu",
  "artifacts.deploy",
  "artifacts.detail.comments",
  "artifacts.detail.versions",
  "artifacts.import",
  "artifacts.new",
  "artifacts.new-folder",
  "artifacts.starred",
  "backup.export",
  "backup.import-file",
  "chat.memory-mode",
  "chat.mobile-sessions-toggle",
  "chat.model-picker",
  "chat.new-session",
  "chat.older-sessions",
  "chat.session-title",
  "chat.sessions-sidebar-toggle",
  "chat.side-panel-open",
  "chat.side-panel.add",
  "chat.side-panel.browser",
  "chat.start-new-chat",
  "composer.add-menu",
  "composer.add-menu.reference-file",
  "composer.add-menu.screenshot",
  "composer.add-menu.sketch",
  "composer.add-menu.skill",
  "composer.add-menu.slash",
  "composer.add-menu.upload",
  "composer.approval-mode",
  "composer.attach-files",
  "composer.context-usage",
  "composer.expand",
  "composer.send",
  "composer.stop",
  "composer.voice",
  "connections.mcp-servers-tab",
  "mcp.add-custom",
  "mcp.add-server",
  "mcp.probe",
  "members.add-menu",
  "members.add-menu.new-team",
  "members.back",
  "members.details",
  "members.edit",
  "members.new",
  "members.new-advanced",
  "members.permissions",
  "members.roster-list",
  "members.switcher",
  "members.switcher.show-roster",
  "notifications.clear-all",
  "notifications.detail.mark-unread",
  "notifications.mark-all-read",
  "notifications.mute-channel",
  "notifications.page-clear-all",
  "notifications.page-mark-all-read",
  "overview.memory-details",
  "schedule.add-job",
  "schedule.cancel-run",
  "schedule.create-first",
  "schedule.delete",
  "schedule.edit-when",
  "schedule.job-list",
  "schedule.new-folder",
  "schedule.pause",
  "schedule.run-now",
  "schedule.secret-approve",
  "schedule.select-all",
  "schedule.templates",
  "schedule.view-executions",
  "sessions.create-menu",
  "sessions.create-menu.new-folder",
  "sessions.list",
  "sessions.list-menu",
  "sessions.list-menu.add-lanes",
  "sessions.list-menu.clean-up",
  "sessions.list-menu.dashboards",
  "sessions.list-menu.manage-tags",
  "sessions.list-menu.switch-model",
  "sessions.list-menu.view",
  "sessions.row-close",
  "sessions.row-duplicate",
  "sessions.show-all-older",
  "shell.connect-phone",
  "shell.developer",
  "shell.focus-mode",
  "shell.kiro-account",
  "shell.menu-search",
  "shell.mobile-menu",
  "shell.nav-toggle",
  "shell.notifications",
  "shell.notifications.open-inbox",
  "shell.report-problem",
  "shell.search",
  "shell.terminal",
  "shell.terminal-more",
  "shell.terminal-more.position",
  "skills.add",
  "skills.create",
  "skills.refresh"
]

/** Every compiled reveal scope: id -> what kind of container it is and the control that opens it. */
export const GUIDE_REVEAL_SCOPES = {
  "chat.sessions-drawer": {
    "kind": "state",
    "revealer": "chat.mobile-sessions-toggle",
    "state": "sessions_drawer_closed"
  },
  "chat.sessions-sidebar": {
    "kind": "state",
    "revealer": "chat.sessions-sidebar-toggle",
    "state": "sessions_sidebar_collapsed"
  },
  "chat.side-panel": {
    "kind": "state",
    "revealer": "chat.side-panel-open",
    "state": "side_panel_closed"
  },
  "composer.box": {
    "kind": "state",
    "revealer": "composer.expand",
    "state": "composer_collapsed"
  },
  "members.profile": {
    "kind": "state",
    "revealer": "members.edit",
    "state": "crewmate_profile_closed"
  },
  "members.roster": {
    "kind": "state",
    "revealer": "members.switcher.show-roster",
    "state": "crewmate_roster_folded"
  },
  "members.roster-phone": {
    "kind": "state",
    "revealer": "members.back",
    "state": "crewmate_chat_open_phone"
  },
  "menu:apps.sources": {
    "kind": "menu",
    "revealer": "apps.sources"
  },
  "menu:artifacts.add-menu": {
    "kind": "menu",
    "revealer": "artifacts.add-menu"
  },
  "menu:chat.side-panel.add": {
    "kind": "menu",
    "revealer": "chat.side-panel.add"
  },
  "menu:composer.add-menu": {
    "kind": "menu",
    "revealer": "composer.add-menu"
  },
  "menu:members.add-menu": {
    "kind": "menu",
    "revealer": "members.add-menu"
  },
  "menu:members.switcher": {
    "kind": "menu",
    "revealer": "members.switcher"
  },
  "menu:sessions.create-menu": {
    "kind": "menu",
    "revealer": "sessions.create-menu"
  },
  "menu:sessions.list-menu": {
    "kind": "menu",
    "revealer": "sessions.list-menu"
  },
  "menu:shell.mobile-menu": {
    "kind": "menu",
    "revealer": "shell.mobile-menu"
  },
  "menu:shell.notifications": {
    "kind": "menu",
    "revealer": "shell.notifications"
  },
  "menu:shell.terminal-more": {
    "kind": "menu",
    "revealer": "shell.terminal-more"
  },
  "open:apps.library.tile-details": {
    "kind": "open",
    "revealer": "apps.library.tile-details"
  },
  "open:chat.older-sessions": {
    "kind": "open",
    "revealer": "chat.older-sessions"
  },
  "open:connections.mcp-servers-tab": {
    "kind": "open",
    "revealer": "connections.mcp-servers-tab"
  },
  "shell.nav-rail": {
    "kind": "state",
    "revealer": "shell.nav-toggle",
    "state": "nav_rail_collapsed"
  },
  "shell.terminal-panel": {
    "kind": "state",
    "revealer": "shell.terminal",
    "state": "terminal_panel_closed"
  }
} as const

/** A reveal scope id of this build: the only ids a `<GuideRevealScope>` owner may report. */
export type GuideRevealScopeId = keyof typeof GUIDE_REVEAL_SCOPES

export const GUIDE_PLANS: Readonly<Record<string, UiGuidePlan>> = {
  "agents.add": {
    "version": 2,
    "label_key": "pages.kiroCrewAgentsPage.add_crew_member",
    "placements": [
      {
        "id": "any",
        "route": "/capabilities?tab=crews",
        "steps": [
          {
            "id": "any:agents.add",
            "location": "agents.add",
            "label_key": "pages.kiroCrewAgentsPage.add_crew_member"
          }
        ]
      }
    ]
  },
  "apps.refresh-store": {
    "version": 2,
    "label_key": "pages.appsPage.refresh_store",
    "placements": [
      {
        "id": "any",
        "route": "/apps",
        "steps": [
          {
            "id": "any:apps.refresh-store",
            "location": "apps.refresh-store",
            "label_key": "pages.appsPage.refresh_store"
          }
        ]
      }
    ]
  },
  "apps.sources": {
    "version": 2,
    "label_key": "components.appstore.sourcesPopover.manage_app_sources",
    "placements": [
      {
        "id": "any",
        "route": "/apps",
        "steps": [
          {
            "id": "any:apps.sources",
            "location": "apps.sources",
            "label_key": "components.appstore.sourcesPopover.manage_app_sources"
          }
        ]
      }
    ]
  },
  "apps.sources.add-registry": {
    "version": 2,
    "label_key": "components.registryManager.add_registry",
    "placements": [
      {
        "id": "any",
        "route": "/apps",
        "steps": [
          {
            "id": "any:apps.sources",
            "location": "apps.sources",
            "label_key": "components.appstore.sourcesPopover.manage_app_sources",
            "scope": "menu:apps.sources"
          },
          {
            "id": "any:apps.sources.add-registry",
            "location": "apps.sources.add-registry",
            "label_key": "components.registryManager.add_registry"
          }
        ]
      }
    ]
  },
  "artifacts.add-menu": {
    "version": 2,
    "label_key": "pages.artifactsPage.more_ways_to_add_an_artifact",
    "placements": [
      {
        "id": "desktop",
        "route": "/artifacts",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:artifacts.add-menu",
            "location": "artifacts.add-menu",
            "label_key": "pages.artifactsPage.more_ways_to_add_an_artifact"
          }
        ]
      }
    ]
  },
  "artifacts.import": {
    "version": 2,
    "label_key": "pages.artifactsPage.import_from_a_file",
    "placements": [
      {
        "id": "desktop",
        "route": "/artifacts",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:artifacts.add-menu",
            "location": "artifacts.add-menu",
            "label_key": "pages.artifactsPage.more_ways_to_add_an_artifact",
            "scope": "menu:artifacts.add-menu"
          },
          {
            "id": "desktop:artifacts.import",
            "location": "artifacts.import",
            "label_key": "pages.artifactsPage.import_from_a_file"
          }
        ]
      }
    ]
  },
  "artifacts.new": {
    "version": 2,
    "label_key": "pages.artifactsPage.new_artifact",
    "placements": [
      {
        "id": "any",
        "route": "/artifacts",
        "steps": [
          {
            "id": "any:artifacts.new",
            "location": "artifacts.new",
            "label_key": "pages.artifactsPage.new_artifact"
          }
        ]
      }
    ]
  },
  "artifacts.new-folder": {
    "version": 2,
    "label_key": "pages.artifactsPage.new_folder",
    "placements": [
      {
        "id": "desktop",
        "route": "/artifacts",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:artifacts.new-folder",
            "location": "artifacts.new-folder",
            "label_key": "pages.artifactsPage.new_folder"
          }
        ]
      }
    ]
  },
  "artifacts.starred": {
    "version": 2,
    "label_key": "pages.artifactsPage.starred",
    "placements": [
      {
        "id": "any",
        "route": "/artifacts",
        "steps": [
          {
            "id": "any:artifacts.starred",
            "location": "artifacts.starred",
            "label_key": "pages.artifactsPage.starred"
          }
        ]
      }
    ]
  },
  "backup.export": {
    "version": 2,
    "label_key": "pages.overview.portabilityTab.download_export_zip",
    "placements": [
      {
        "id": "any",
        "route": "/settings/imports",
        "steps": [
          {
            "id": "any:backup.export",
            "location": "backup.export",
            "label_key": "pages.overview.portabilityTab.download_export_zip"
          }
        ]
      }
    ]
  },
  "chat.mobile-sessions-toggle": {
    "version": 2,
    "label_key": "pages.chatPage.toggle_sessions",
    "placements": [
      {
        "id": "mobile",
        "route": "/chat",
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:chat.mobile-sessions-toggle",
            "location": "chat.mobile-sessions-toggle",
            "label_key": "pages.chatPage.toggle_sessions"
          }
        ]
      }
    ]
  },
  "chat.new-session": {
    "version": 2,
    "label_key": "pages.chatSidebar.new_chat_session",
    "placements": [
      {
        "id": "desktop",
        "route": "/chat",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:chat.sessions-sidebar-toggle",
            "location": "chat.sessions-sidebar-toggle",
            "label_key": "pages.chatPage.show_sessions_sidebar",
            "when": "sessions_sidebar_collapsed",
            "scope": "chat.sessions-sidebar",
            "requires": [
              "has_open_sessions",
              "full_dashboard"
            ]
          },
          {
            "id": "desktop:chat.new-session",
            "location": "chat.new-session",
            "label_key": "pages.chatSidebar.new_chat_session"
          }
        ]
      },
      {
        "id": "mobile",
        "route": "/chat",
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:chat.mobile-sessions-toggle",
            "location": "chat.mobile-sessions-toggle",
            "label_key": "pages.chatPage.toggle_sessions",
            "when": "sessions_drawer_closed",
            "scope": "chat.sessions-drawer"
          },
          {
            "id": "mobile:chat.new-session",
            "location": "chat.new-session",
            "label_key": "pages.chatSidebar.new_chat_session"
          }
        ]
      }
    ]
  },
  "chat.older-sessions": {
    "version": 2,
    "label_key": "pages.chatSidebar.older_sessions_2",
    "placements": [
      {
        "id": "desktop",
        "route": "/chat",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:chat.sessions-sidebar-toggle",
            "location": "chat.sessions-sidebar-toggle",
            "label_key": "pages.chatPage.show_sessions_sidebar",
            "when": "sessions_sidebar_collapsed",
            "scope": "chat.sessions-sidebar",
            "requires": [
              "has_open_sessions",
              "full_dashboard"
            ]
          },
          {
            "id": "desktop:chat.older-sessions",
            "location": "chat.older-sessions",
            "label_key": "pages.chatSidebar.older_sessions_2"
          }
        ]
      },
      {
        "id": "mobile",
        "route": "/chat",
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:chat.mobile-sessions-toggle",
            "location": "chat.mobile-sessions-toggle",
            "label_key": "pages.chatPage.toggle_sessions",
            "when": "sessions_drawer_closed",
            "scope": "chat.sessions-drawer"
          },
          {
            "id": "mobile:chat.older-sessions",
            "location": "chat.older-sessions",
            "label_key": "pages.chatSidebar.older_sessions_2"
          }
        ]
      }
    ]
  },
  "chat.side-panel-open": {
    "version": 2,
    "label_key": "pages.chatPage.open_activity_panel",
    "placements": [
      {
        "id": "desktop",
        "route": "/chat",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:chat.sessions-sidebar-toggle",
            "location": "chat.sessions-sidebar-toggle",
            "label_key": "pages.chatPage.show_sessions_sidebar",
            "when": "sessions_sidebar_collapsed",
            "scope": "chat.sessions-sidebar",
            "requires": [
              "has_open_sessions",
              "full_dashboard"
            ]
          },
          {
            "id": "desktop:select:session_open",
            "kind": "select",
            "location": "sessions.list",
            "label_key": "pages.chatSidebar.sessions",
            "selection": "session_open",
            "entity": "session"
          },
          {
            "id": "desktop:chat.side-panel-open",
            "location": "chat.side-panel-open",
            "label_key": "pages.chatPage.open_activity_panel"
          }
        ]
      }
    ]
  },
  "composer.expand": {
    "version": 2,
    "label_key": "components.chatInput.expand_composer",
    "placements": [
      {
        "id": "desktop",
        "route": "/chat",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:chat.sessions-sidebar-toggle",
            "location": "chat.sessions-sidebar-toggle",
            "label_key": "pages.chatPage.show_sessions_sidebar",
            "when": "sessions_sidebar_collapsed",
            "scope": "chat.sessions-sidebar",
            "requires": [
              "has_open_sessions",
              "full_dashboard"
            ]
          },
          {
            "id": "desktop:select:session_open",
            "kind": "select",
            "location": "sessions.list",
            "label_key": "pages.chatSidebar.sessions",
            "selection": "session_open",
            "entity": "session"
          },
          {
            "id": "desktop:composer.expand",
            "location": "composer.expand",
            "label_key": "components.chatInput.expand_composer"
          }
        ]
      },
      {
        "id": "mobile",
        "route": "/chat",
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:chat.mobile-sessions-toggle",
            "location": "chat.mobile-sessions-toggle",
            "label_key": "pages.chatPage.toggle_sessions",
            "when": "sessions_drawer_closed",
            "scope": "chat.sessions-drawer"
          },
          {
            "id": "mobile:select:session_open",
            "kind": "select",
            "location": "sessions.list",
            "label_key": "pages.chatSidebar.sessions",
            "selection": "session_open",
            "entity": "session"
          },
          {
            "id": "mobile:composer.expand",
            "location": "composer.expand",
            "label_key": "components.chatInput.expand_composer"
          }
        ]
      }
    ]
  },
  "connections.mcp-servers-tab": {
    "version": 2,
    "label_key": "pages.connectionsPage.mcp_servers",
    "placements": [
      {
        "id": "any",
        "route": "/capabilities?tab=mcp",
        "steps": [
          {
            "id": "any:connections.mcp-servers-tab",
            "location": "connections.mcp-servers-tab",
            "label_key": "pages.connectionsPage.mcp_servers"
          }
        ]
      }
    ]
  },
  "mcp.add-server": {
    "version": 2,
    "label_key": "pages.overview.mcpTab.add_server",
    "placements": [
      {
        "id": "any",
        "route": "/capabilities?tab=mcp",
        "steps": [
          {
            "id": "any:connections.mcp-servers-tab",
            "location": "connections.mcp-servers-tab",
            "label_key": "pages.connectionsPage.mcp_servers",
            "scope": "open:connections.mcp-servers-tab"
          },
          {
            "id": "any:mcp.add-server",
            "location": "mcp.add-server",
            "label_key": "pages.overview.mcpTab.add_server"
          }
        ]
      }
    ]
  },
  "mcp.probe": {
    "version": 2,
    "label_key": "pages.overview.mcpTab.probe_mcp_servers",
    "placements": [
      {
        "id": "any",
        "route": "/capabilities?tab=mcp",
        "steps": [
          {
            "id": "any:connections.mcp-servers-tab",
            "location": "connections.mcp-servers-tab",
            "label_key": "pages.connectionsPage.mcp_servers",
            "scope": "open:connections.mcp-servers-tab"
          },
          {
            "id": "any:mcp.probe",
            "location": "mcp.probe",
            "label_key": "pages.overview.mcpTab.probe_mcp_servers"
          }
        ]
      }
    ]
  },
  "members.back": {
    "version": 2,
    "label_key": "pages.membersPage.back_to_roster",
    "placements": [
      {
        "id": "mobile",
        "route": "/members",
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:select:crewmate_selected",
            "kind": "select",
            "location": "members.roster-list",
            "label_key": "pages.membersPage.title",
            "selection": "crewmate_selected",
            "entity": "crewmate"
          },
          {
            "id": "mobile:members.back",
            "location": "members.back",
            "label_key": "pages.membersPage.back_to_roster"
          }
        ]
      }
    ]
  },
  "members.edit": {
    "version": 2,
    "label_key": "pages.membersPage.profile_card",
    "placements": [
      {
        "id": "any",
        "route": "/members",
        "steps": [
          {
            "id": "any:select:crewmate_selected",
            "kind": "select",
            "location": "members.roster-list",
            "label_key": "pages.membersPage.title",
            "selection": "crewmate_selected",
            "entity": "crewmate"
          },
          {
            "id": "any:members.edit",
            "location": "members.edit",
            "label_key": "pages.membersPage.profile_card"
          }
        ]
      }
    ]
  },
  "members.permissions": {
    "version": 2,
    "label_key": "pages.membersPage.profile_permissions",
    "placements": [
      {
        "id": "any",
        "route": "/members",
        "steps": [
          {
            "id": "any:select:crewmate_selected",
            "kind": "select",
            "location": "members.roster-list",
            "label_key": "pages.membersPage.title",
            "selection": "crewmate_selected",
            "entity": "crewmate"
          },
          {
            "id": "any:members.edit",
            "location": "members.edit",
            "label_key": "pages.membersPage.profile_card",
            "when": "crewmate_profile_closed",
            "scope": "members.profile"
          },
          {
            "id": "any:members.permissions",
            "location": "members.permissions",
            "label_key": "pages.membersPage.profile_permissions"
          }
        ]
      }
    ]
  },
  "members.switcher": {
    "version": 2,
    "label_key": "pages.membersPage.switch_crewmate",
    "placements": [
      {
        "id": "desktop",
        "route": "/members",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:select:crewmate_selected",
            "kind": "select",
            "location": "members.roster-list",
            "label_key": "pages.membersPage.title",
            "selection": "crewmate_selected",
            "entity": "crewmate"
          },
          {
            "id": "desktop:members.switcher",
            "location": "members.switcher",
            "label_key": "pages.membersPage.switch_crewmate"
          }
        ]
      }
    ]
  },
  "members.switcher.show-roster": {
    "version": 2,
    "label_key": "pages.membersPage.roster_show",
    "placements": [
      {
        "id": "desktop",
        "route": "/members",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:select:crewmate_selected",
            "kind": "select",
            "location": "members.roster-list",
            "label_key": "pages.membersPage.title",
            "selection": "crewmate_selected",
            "entity": "crewmate"
          },
          {
            "id": "desktop:members.switcher",
            "location": "members.switcher",
            "label_key": "pages.membersPage.switch_crewmate",
            "scope": "menu:members.switcher"
          },
          {
            "id": "desktop:members.switcher.show-roster",
            "location": "members.switcher.show-roster",
            "label_key": "pages.membersPage.roster_show"
          }
        ]
      }
    ]
  },
  "overview.memory-details": {
    "version": 2,
    "label_key": "pages.overviewPage.view_details",
    "placements": [
      {
        "id": "any",
        "route": "/settings/overview",
        "steps": [
          {
            "id": "any:overview.memory-details",
            "location": "overview.memory-details",
            "label_key": "pages.overviewPage.view_details"
          }
        ]
      }
    ]
  },
  "schedule.pause": {
    "version": 2,
    "label_key": "pages.schedulePage.pause",
    "placements": [
      {
        "id": "any",
        "route": "/schedule",
        "steps": [
          {
            "id": "any:select:job_open",
            "kind": "select",
            "location": "schedule.job-list",
            "label_key": "pages.schedulePage.jobs_table",
            "selection": "job_open",
            "entity": "job",
            "requires": [
              "schedule_list_view"
            ]
          },
          {
            "id": "any:schedule.pause",
            "location": "schedule.pause",
            "label_key": "pages.schedulePage.pause"
          }
        ]
      }
    ]
  },
  "schedule.view-executions": {
    "version": 2,
    "label_key": "pages.schedulePage.view_executions",
    "placements": [
      {
        "id": "any",
        "route": "/schedule",
        "steps": [
          {
            "id": "any:schedule.view-executions",
            "location": "schedule.view-executions",
            "label_key": "pages.schedulePage.view_executions"
          }
        ]
      }
    ]
  },
  "sessions.create-menu": {
    "version": 2,
    "label_key": "pages.chatSidebar.more_create_options",
    "placements": [
      {
        "id": "desktop",
        "route": "/chat",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:chat.sessions-sidebar-toggle",
            "location": "chat.sessions-sidebar-toggle",
            "label_key": "pages.chatPage.show_sessions_sidebar",
            "when": "sessions_sidebar_collapsed",
            "scope": "chat.sessions-sidebar",
            "requires": [
              "has_open_sessions",
              "full_dashboard"
            ]
          },
          {
            "id": "desktop:sessions.create-menu",
            "location": "sessions.create-menu",
            "label_key": "pages.chatSidebar.more_create_options"
          }
        ]
      },
      {
        "id": "mobile",
        "route": "/chat",
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:chat.mobile-sessions-toggle",
            "location": "chat.mobile-sessions-toggle",
            "label_key": "pages.chatPage.toggle_sessions",
            "when": "sessions_drawer_closed",
            "scope": "chat.sessions-drawer"
          },
          {
            "id": "mobile:sessions.create-menu",
            "location": "sessions.create-menu",
            "label_key": "pages.chatSidebar.more_create_options"
          }
        ]
      }
    ]
  },
  "sessions.create-menu.new-folder": {
    "version": 2,
    "label_key": "pages.chatSidebar.new_folder",
    "placements": [
      {
        "id": "desktop",
        "route": "/chat",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:chat.sessions-sidebar-toggle",
            "location": "chat.sessions-sidebar-toggle",
            "label_key": "pages.chatPage.show_sessions_sidebar",
            "when": "sessions_sidebar_collapsed",
            "scope": "chat.sessions-sidebar",
            "requires": [
              "has_open_sessions",
              "full_dashboard"
            ]
          },
          {
            "id": "desktop:sessions.create-menu",
            "location": "sessions.create-menu",
            "label_key": "pages.chatSidebar.more_create_options",
            "scope": "menu:sessions.create-menu"
          },
          {
            "id": "desktop:sessions.create-menu.new-folder",
            "location": "sessions.create-menu.new-folder",
            "label_key": "pages.chatSidebar.new_folder"
          }
        ]
      },
      {
        "id": "mobile",
        "route": "/chat",
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:chat.mobile-sessions-toggle",
            "location": "chat.mobile-sessions-toggle",
            "label_key": "pages.chatPage.toggle_sessions",
            "when": "sessions_drawer_closed",
            "scope": "chat.sessions-drawer"
          },
          {
            "id": "mobile:sessions.create-menu",
            "location": "sessions.create-menu",
            "label_key": "pages.chatSidebar.more_create_options",
            "scope": "menu:sessions.create-menu"
          },
          {
            "id": "mobile:sessions.create-menu.new-folder",
            "location": "sessions.create-menu.new-folder",
            "label_key": "pages.chatSidebar.new_folder"
          }
        ]
      }
    ]
  },
  "sessions.list-menu": {
    "version": 2,
    "label_key": "pages.chatSidebar.more_options",
    "placements": [
      {
        "id": "desktop",
        "route": "/chat",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:chat.sessions-sidebar-toggle",
            "location": "chat.sessions-sidebar-toggle",
            "label_key": "pages.chatPage.show_sessions_sidebar",
            "when": "sessions_sidebar_collapsed",
            "scope": "chat.sessions-sidebar",
            "requires": [
              "has_open_sessions",
              "full_dashboard"
            ]
          },
          {
            "id": "desktop:sessions.list-menu",
            "location": "sessions.list-menu",
            "label_key": "pages.chatSidebar.more_options"
          }
        ]
      },
      {
        "id": "mobile",
        "route": "/chat",
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:chat.mobile-sessions-toggle",
            "location": "chat.mobile-sessions-toggle",
            "label_key": "pages.chatPage.toggle_sessions",
            "when": "sessions_drawer_closed",
            "scope": "chat.sessions-drawer"
          },
          {
            "id": "mobile:sessions.list-menu",
            "location": "sessions.list-menu",
            "label_key": "pages.chatSidebar.more_options"
          }
        ]
      }
    ]
  },
  "sessions.list-menu.dashboards": {
    "version": 2,
    "label_key": "commandCenter.all_title",
    "placements": [
      {
        "id": "desktop",
        "route": "/chat",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:chat.sessions-sidebar-toggle",
            "location": "chat.sessions-sidebar-toggle",
            "label_key": "pages.chatPage.show_sessions_sidebar",
            "when": "sessions_sidebar_collapsed",
            "scope": "chat.sessions-sidebar",
            "requires": [
              "has_open_sessions",
              "full_dashboard"
            ]
          },
          {
            "id": "desktop:sessions.list-menu",
            "location": "sessions.list-menu",
            "label_key": "pages.chatSidebar.more_options",
            "scope": "menu:sessions.list-menu"
          },
          {
            "id": "desktop:sessions.list-menu.dashboards",
            "location": "sessions.list-menu.dashboards",
            "label_key": "commandCenter.all_title"
          }
        ]
      },
      {
        "id": "mobile",
        "route": "/chat",
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:chat.mobile-sessions-toggle",
            "location": "chat.mobile-sessions-toggle",
            "label_key": "pages.chatPage.toggle_sessions",
            "when": "sessions_drawer_closed",
            "scope": "chat.sessions-drawer"
          },
          {
            "id": "mobile:sessions.list-menu",
            "location": "sessions.list-menu",
            "label_key": "pages.chatSidebar.more_options",
            "scope": "menu:sessions.list-menu"
          },
          {
            "id": "mobile:sessions.list-menu.dashboards",
            "location": "sessions.list-menu.dashboards",
            "label_key": "commandCenter.all_title"
          }
        ]
      }
    ]
  },
  "sessions.list-menu.manage-tags": {
    "version": 2,
    "label_key": "pages.chatSidebar.manage_tags",
    "placements": [
      {
        "id": "desktop",
        "route": "/chat",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:chat.sessions-sidebar-toggle",
            "location": "chat.sessions-sidebar-toggle",
            "label_key": "pages.chatPage.show_sessions_sidebar",
            "when": "sessions_sidebar_collapsed",
            "scope": "chat.sessions-sidebar",
            "requires": [
              "has_open_sessions",
              "full_dashboard"
            ]
          },
          {
            "id": "desktop:sessions.list-menu",
            "location": "sessions.list-menu",
            "label_key": "pages.chatSidebar.more_options",
            "scope": "menu:sessions.list-menu"
          },
          {
            "id": "desktop:sessions.list-menu.manage-tags",
            "location": "sessions.list-menu.manage-tags",
            "label_key": "pages.chatSidebar.manage_tags"
          }
        ]
      },
      {
        "id": "mobile",
        "route": "/chat",
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:chat.mobile-sessions-toggle",
            "location": "chat.mobile-sessions-toggle",
            "label_key": "pages.chatPage.toggle_sessions",
            "when": "sessions_drawer_closed",
            "scope": "chat.sessions-drawer"
          },
          {
            "id": "mobile:sessions.list-menu",
            "location": "sessions.list-menu",
            "label_key": "pages.chatSidebar.more_options",
            "scope": "menu:sessions.list-menu"
          },
          {
            "id": "mobile:sessions.list-menu.manage-tags",
            "location": "sessions.list-menu.manage-tags",
            "label_key": "pages.chatSidebar.manage_tags"
          }
        ]
      }
    ]
  },
  "sessions.list-menu.switch-model": {
    "version": 2,
    "label_key": "pages.chatSidebar.switch_all_to_model",
    "placements": [
      {
        "id": "desktop",
        "route": "/chat",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:chat.sessions-sidebar-toggle",
            "location": "chat.sessions-sidebar-toggle",
            "label_key": "pages.chatPage.show_sessions_sidebar",
            "when": "sessions_sidebar_collapsed",
            "scope": "chat.sessions-sidebar",
            "requires": [
              "has_open_sessions",
              "full_dashboard"
            ]
          },
          {
            "id": "desktop:sessions.list-menu",
            "location": "sessions.list-menu",
            "label_key": "pages.chatSidebar.more_options",
            "scope": "menu:sessions.list-menu"
          },
          {
            "id": "desktop:sessions.list-menu.switch-model",
            "location": "sessions.list-menu.switch-model",
            "label_key": "pages.chatSidebar.switch_all_to_model"
          }
        ]
      },
      {
        "id": "mobile",
        "route": "/chat",
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:chat.mobile-sessions-toggle",
            "location": "chat.mobile-sessions-toggle",
            "label_key": "pages.chatPage.toggle_sessions",
            "when": "sessions_drawer_closed",
            "scope": "chat.sessions-drawer"
          },
          {
            "id": "mobile:sessions.list-menu",
            "location": "sessions.list-menu",
            "label_key": "pages.chatSidebar.more_options",
            "scope": "menu:sessions.list-menu"
          },
          {
            "id": "mobile:sessions.list-menu.switch-model",
            "location": "sessions.list-menu.switch-model",
            "label_key": "pages.chatSidebar.switch_all_to_model"
          }
        ]
      }
    ]
  },
  "sessions.list-menu.view": {
    "version": 2,
    "label_key": "pages.chatSidebar.switch_to_board_view",
    "placements": [
      {
        "id": "desktop",
        "route": "/chat",
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:chat.sessions-sidebar-toggle",
            "location": "chat.sessions-sidebar-toggle",
            "label_key": "pages.chatPage.show_sessions_sidebar",
            "when": "sessions_sidebar_collapsed",
            "scope": "chat.sessions-sidebar",
            "requires": [
              "has_open_sessions",
              "full_dashboard"
            ]
          },
          {
            "id": "desktop:sessions.list-menu",
            "location": "sessions.list-menu",
            "label_key": "pages.chatSidebar.more_options",
            "scope": "menu:sessions.list-menu"
          },
          {
            "id": "desktop:sessions.list-menu.view",
            "location": "sessions.list-menu.view",
            "label_key": "pages.chatSidebar.switch_to_board_view"
          }
        ]
      },
      {
        "id": "mobile",
        "route": "/chat",
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:chat.mobile-sessions-toggle",
            "location": "chat.mobile-sessions-toggle",
            "label_key": "pages.chatPage.toggle_sessions",
            "when": "sessions_drawer_closed",
            "scope": "chat.sessions-drawer"
          },
          {
            "id": "mobile:sessions.list-menu",
            "location": "sessions.list-menu",
            "label_key": "pages.chatSidebar.more_options",
            "scope": "menu:sessions.list-menu"
          },
          {
            "id": "mobile:sessions.list-menu.view",
            "location": "sessions.list-menu.view",
            "label_key": "pages.chatSidebar.switch_to_board_view"
          }
        ]
      }
    ]
  },
  "shell.developer": {
    "version": 2,
    "label_key": "app.developer",
    "placements": [
      {
        "id": "desktop",
        "route": null,
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:gate:developer_mode",
            "kind": "gate",
            "gate": "developer_mode",
            "setting_id": "developer.developer-mode"
          },
          {
            "id": "desktop:shell.developer",
            "location": "shell.developer",
            "label_key": "app.developer"
          }
        ]
      },
      {
        "id": "mobile",
        "route": null,
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:gate:developer_mode",
            "kind": "gate",
            "gate": "developer_mode",
            "setting_id": "developer.developer-mode"
          },
          {
            "id": "mobile:shell.mobile-menu",
            "location": "shell.mobile-menu",
            "label_key": "app.open_menu",
            "scope": "menu:shell.mobile-menu",
            "requires": [
              "not_on_sessions_page"
            ]
          },
          {
            "id": "mobile:shell.developer",
            "location": "shell.developer",
            "label_key": "app.developer"
          }
        ]
      }
    ]
  },
  "shell.focus-mode": {
    "version": 2,
    "label_key": "app.focus_mode",
    "placements": [
      {
        "id": "desktop",
        "route": null,
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:shell.focus-mode",
            "location": "shell.focus-mode",
            "label_key": "app.focus_mode"
          }
        ]
      }
    ]
  },
  "shell.nav-toggle": {
    "version": 2,
    "label_key": "app.expand_sidebar",
    "placements": [
      {
        "id": "desktop",
        "route": null,
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:shell.nav-toggle",
            "location": "shell.nav-toggle",
            "label_key": "app.expand_sidebar"
          }
        ]
      }
    ]
  },
  "shell.notifications": {
    "version": 2,
    "label_key": "app.notifications",
    "placements": [
      {
        "id": "any",
        "route": null,
        "steps": [
          {
            "id": "any:shell.notifications",
            "location": "shell.notifications",
            "label_key": "app.notifications"
          }
        ]
      }
    ]
  },
  "shell.notifications.open-inbox": {
    "version": 2,
    "label_key": "app.open_inbox",
    "placements": [
      {
        "id": "any",
        "route": null,
        "steps": [
          {
            "id": "any:shell.notifications",
            "location": "shell.notifications",
            "label_key": "app.notifications",
            "scope": "menu:shell.notifications"
          },
          {
            "id": "any:shell.notifications.open-inbox",
            "location": "shell.notifications.open-inbox",
            "label_key": "app.open_inbox"
          }
        ]
      }
    ]
  },
  "shell.report-problem": {
    "version": 2,
    "label_key": "app.report_issue",
    "placements": [
      {
        "id": "desktop",
        "route": null,
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:shell.nav-toggle",
            "location": "shell.nav-toggle",
            "label_key": "app.expand_sidebar",
            "when": "nav_rail_collapsed",
            "scope": "shell.nav-rail"
          },
          {
            "id": "desktop:shell.report-problem",
            "location": "shell.report-problem",
            "label_key": "app.report_issue"
          }
        ]
      },
      {
        "id": "mobile",
        "route": null,
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:shell.mobile-menu",
            "location": "shell.mobile-menu",
            "label_key": "app.open_menu",
            "scope": "menu:shell.mobile-menu",
            "requires": [
              "not_on_sessions_page"
            ]
          },
          {
            "id": "mobile:shell.report-problem",
            "location": "shell.report-problem",
            "label_key": "app.report_issue"
          }
        ]
      }
    ]
  },
  "shell.terminal": {
    "version": 2,
    "label_key": "app.terminal",
    "placements": [
      {
        "id": "desktop",
        "route": null,
        "viewport": "desktop",
        "steps": [
          {
            "id": "desktop:gate:terminal_enabled",
            "kind": "gate",
            "gate": "terminal_enabled"
          },
          {
            "id": "desktop:shell.terminal",
            "location": "shell.terminal",
            "label_key": "app.terminal"
          }
        ]
      },
      {
        "id": "mobile",
        "route": null,
        "viewport": "mobile",
        "steps": [
          {
            "id": "mobile:gate:terminal_enabled",
            "kind": "gate",
            "gate": "terminal_enabled"
          },
          {
            "id": "mobile:shell.mobile-menu",
            "location": "shell.mobile-menu",
            "label_key": "app.open_menu",
            "scope": "menu:shell.mobile-menu",
            "requires": [
              "not_on_sessions_page"
            ]
          },
          {
            "id": "mobile:shell.terminal",
            "location": "shell.terminal",
            "label_key": "app.terminal"
          }
        ]
      }
    ]
  },
  "skills.add": {
    "version": 2,
    "label_key": "pages.overview.skillsTab.add_skill",
    "placements": [
      {
        "id": "any",
        "route": "/capabilities?tab=skills",
        "steps": [
          {
            "id": "any:skills.add",
            "location": "skills.add",
            "label_key": "pages.overview.skillsTab.add_skill"
          }
        ]
      }
    ]
  },
  "skills.create": {
    "version": 2,
    "label_key": "pages.overview.skillsTab.create_new_skill",
    "placements": [
      {
        "id": "any",
        "route": "/capabilities?tab=skills",
        "steps": [
          {
            "id": "any:skills.create",
            "location": "skills.create",
            "label_key": "pages.overview.skillsTab.create_new_skill"
          }
        ]
      }
    ]
  },
  "skills.refresh": {
    "version": 2,
    "label_key": "pages.overview.skillsTab.refresh_skills",
    "placements": [
      {
        "id": "any",
        "route": "/capabilities?tab=skills",
        "steps": [
          {
            "id": "any:skills.refresh",
            "location": "skills.refresh",
            "label_key": "pages.overview.skillsTab.refresh_skills"
          }
        ]
      }
    ]
  }
}
