"""The run-hook payload's wire shape, as the guest reads it.

A VERBATIM copy of ``decode_payload`` / ``payload_encoding`` /
``_decode_with_encoding`` from ``kiro_crew/cloud/microvm/payload.py``, which is
the lane's definition and the only place the shape is decided.

It is copied rather than imported because the container package is a separate
source root that ships inside an image: ``kiro_crew`` is installed in that image
as a wheel, but importing the gateway's cloud module from the guest would pull
the control plane's code into the customer-facing container, which is exactly
what ``runtime/Dockerfile`` narrows its COPY to prevent.

``test_microvm_payload_shape_matches_the_lane`` asserts the two are
byte-identical, so a change to the lane's decoder fails the suite here rather
than shipping a guest that reads a different wire format from the launcher that
writes it. Do not edit this file: edit the lane's and re-copy.
"""

from __future__ import annotations

import json
from typing import Any, Optional


def decode_payload(text: "str | bytes") -> dict[str, Any]:
    """Read a payload back, as the guest does.

    Here rather than in the guest's own source so the two shapes are pinned by one
    test: a payload the launcher can write and the guest cannot read is a VM that
    boots, registers nothing and bills for eight hours. Which is exactly what
    happened live, three launches in a row, before this function knew
    the shape the guest is actually handed.

    **The platform does not deliver what the launcher wrote.** ``RunMicrovm``
    takes ``runHookPayload`` as a JSON string, and the run hook receives that
    string BASE64-ENCODED. Measured: a 434-byte payload arrived at the hook as a
    576-byte body, and 576 is the base64 length of 432 bytes. Nothing in the API
    reference says so, and a guest that calls ``json.loads`` on the body gets a
    decode error with no hint of why -- which reads exactly like a launcher bug.

    So three forms are accepted, in order, and the one that worked is recorded by
    :func:`payload_encoding` for a caller that wants to log it:

    1. raw JSON, which is what the launcher wrote and what a local harness
       delivers;
    2. base64 of that JSON, which is what the real platform delivers;
    3. a JSON envelope with the payload under ``payload`` or ``runHookPayload``,
       in either of the two forms above -- accepted defensively rather than
       because it was observed, since a platform that wraps once may wrap again.

    Being liberal here is the right direction: every form is checked for
    ``v == 1`` before it is believed, so a body this function cannot read is
    refused rather than guessed at.
    """
    data, _ = _decode_with_encoding(text)
    return data


def payload_encoding(text: "str | bytes") -> str:
    """Which of the accepted forms *text* is: ``json``, ``base64``, ``envelope``.

    Exists so a guest can LOG the form it received without logging the payload
    itself -- the payload carries a single-use activation code, so its content
    must not reach a log, and "which encoding arrived" is the one fact about it
    that is both safe and diagnostic.
    """
    return _decode_with_encoding(text)[1]


def _decode_with_encoding(text: "str | bytes") -> tuple[dict[str, Any], str]:
    raw = text.decode("utf-8", "replace") if isinstance(text, bytes) else text
    candidate = raw.strip()

    def _as_v1(value: object) -> Optional[dict[str, Any]]:
        return value if isinstance(value, dict) and value.get("v") == 1 else None

    direct: object = None
    try:
        direct = json.loads(candidate)
    except (ValueError, TypeError):
        direct = None
    found = _as_v1(direct)
    if found is not None:
        return found, "json"

    import base64
    import binascii

    try:
        # ``validate=True``: without it, base64 silently discards any character
        # outside the alphabet, so a JSON document that failed to parse above
        # would be "decoded" into bytes that are not it.
        decoded = base64.b64decode(candidate, validate=True).decode("utf-8")
        found = _as_v1(json.loads(decoded))
        if found is not None:
            return found, "base64"
    except (binascii.Error, ValueError, TypeError, UnicodeDecodeError):
        pass

    if isinstance(direct, dict):
        for key in ("payload", "runHookPayload"):
            inner = direct.get(key)
            if isinstance(inner, (str, bytes)):
                try:
                    nested, _ = _decode_with_encoding(inner)
                except ValueError:
                    continue
                return nested, "envelope"

    raise ValueError(
        "not a version-1 MicroVM run hook payload: the body is neither JSON, nor "
        "base64 of JSON, nor an envelope carrying either. The platform delivers "
        "the launcher's string base64-encoded, so a raw-JSON-only reader fails here "
        "on every real launch"
    )
