// AUTO-GENERATED by scripts/gen-settings-registry.mjs — DO NOT EDIT
// Re-generate with: npm run gen:settings

import type { SettingEntry } from './settingsTypes'

export const SETTINGS_REGISTRY: SettingEntry[] = 
[
  {
    "id": "browser.chrome-extension-mode",
    "label": "Chrome Extension Mode",
    "description": "Attach to your running Chrome with all existing logins and sessions. Recommended for macOS.",
    "tab": "browser",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "browser.connection-token",
    "label": "Connection Token",
    "description": "Paste PLAYWRIGHT_MCP_EXTENSION_TOKEN value from the extension popup",
    "tab": "browser",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "chat.auto-compact-threshold",
    "label": "Auto-Compact Threshold",
    "description": "Context usage % at which auto-compaction triggers. Lower = more frequent compaction, longer sessions",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.completion-event-characters",
    "label": "Completion Event Characters",
    "tab": "chat",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "chat.completion-event-truncation",
    "label": "Completion Event Truncation",
    "description": "Which part of a subagent's stream to keep when injecting its completion event into the parent session. Head preserves the start (default, matches legacy behavior). Tail preserves the final summary. Both keeps a slice from each end with a marker between them.",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.confirm-before-closing-session",
    "label": "Confirm Before Closing Session",
    "description": "Show a confirmation dialog when closing a session",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.content-width",
    "label": "Content Width",
    "description": "Compact is the original view. Comfortable and Full use more screen space.",
    "tab": "chat",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "chat.default-to-autopilot-mode",
    "label": "Default to Autopilot Mode",
    "description": "New sessions start in autopilot mode (plan → approve → execute). You can still toggle individual sessions.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.feature-tips",
    "label": "Feature Tips",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.file-change-chips",
    "label": "File Change Chips",
    "description": "How file diff chips appear below assistant messages",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.follow-up-bar-layout",
    "label": "Follow-Up Bar Layout",
    "description": "Multiline wraps suggestions onto multiple rows. Single line keeps them on one horizontally-scrollable row.",
    "tab": "chat",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "chat.history-expanded",
    "label": "History Expanded",
    "description": "Expand history sidebar by default",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.merge-queued-messages",
    "label": "Merge Queued Messages",
    "description": "Combine follow-up messages into a single labeled prompt while the agent is busy",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.notification-limit",
    "label": "Notification Limit",
    "description": "Maximum notifications to display",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.quick-send",
    "label": "Quick Send",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.restore-sessions",
    "label": "Restore Sessions",
    "description": "Re-open recently active sessions on startup",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.restore-window",
    "label": "Restore Window",
    "description": "Time window for session restoration",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.send-shortcut",
    "label": "Send shortcut",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.show-context-percentage",
    "label": "Show Context Percentage",
    "description": "Display usage percentage next to the context progress bar",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.show-thinking-inline",
    "label": "Show Thinking Inline",
    "description": "Show intermediate reasoning text between tool calls instead of collapsing everything",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.show-timestamps",
    "label": "Show Timestamps",
    "description": "Display time on each message",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.simplified-tool-call-names",
    "label": "Simplified Tool Call Names",
    "description": "When enabled, inline tool pills show simplified tool use purpose instead of the exact command being run",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.soft-stop-budget-seconds",
    "label": "Soft-stop budget (seconds)",
    "tab": "chat",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "chat.split-view-session-grid",
    "label": "Split View (Session Grid)",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.tail-only-fork",
    "label": "Tail-only Fork",
    "description": "Fork keeps only the messages after the chosen point instead of those up to it.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.text-streaming-style",
    "label": "Text Streaming Style",
    "description": "Immediate mode shows raw chunks as they arrive. Smooth mode buffers and fades text in at a steady pace.",
    "tab": "chat",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "chat.widget-density",
    "label": "Widget Density",
    "description": "How aggressively the agent uses inline widgets for visual content",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "developer.beta-channel-braveheart",
    "label": "Beta Channel (Braveheart)",
    "description": "Receive early access updates from the braveheart branch. Coming soon.",
    "tab": "developer",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "developer.developer-mode",
    "label": "Developer Mode",
    "description": "Show Developer page in sidebar with Logs, System metrics, and Memory internals",
    "tab": "developer",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "display.display-mode",
    "label": "Display Mode",
    "description": "How the session color is applied to the row.",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.font-family",
    "label": "Font Family",
    "description": "UI font family for the dashboard",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.highlight-recent-sessions",
    "label": "Highlight recent sessions",
    "description": "Highlight the N most-recently-active sessions with a graded accent stripe (0 = off). Saved to your KiroCrew config.",
    "tab": "display",
    "type": "stepper",
    "occurrence": 1
  },
  {
    "id": "display.intensity",
    "label": "Intensity",
    "description": "How visible the color tint is on sidebar rows.",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.interface",
    "label": "Interface",
    "description": "Chat bubbles or CLI-style line-by-line output",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.mode",
    "label": "Mode",
    "description": "Light or dark appearance for the dashboard",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.palette",
    "label": "Palette",
    "description": "Choose a color palette for your sidebar sessions.",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.theme",
    "label": "Theme",
    "description": "Select a theme for the dashboard",
    "tab": "display",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "display.zoom-level",
    "label": "Zoom Level",
    "tab": "display",
    "type": "stepper",
    "occurrence": 1
  },
  {
    "id": "notifications.play-sound-on-new-notifications",
    "label": "Play sound on new notifications",
    "tab": "notifications",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "slack.owner-slack-member-id",
    "label": "Owner Slack member ID",
    "description": "The one member who can always interact with the bot (KIROCREW_OWNER_ID). Starts with U or W.",
    "tab": "slack",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "slack.phase-reactions",
    "label": "Phase reactions",
    "description": "Show phase-aware emoji reactions (queued → thinking → coding → done) on messages.",
    "tab": "slack",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "slack.show-thinking",
    "label": "Show thinking",
    "description": "Post the model's reasoning as a thread reply. Disable to keep responses concise.",
    "tab": "slack",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "slack.slash-command",
    "label": "Slash command",
    "description": "Trigger word for the Slack slash command (without the leading /).",
    "tab": "slack",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.auto-speak-responses",
    "label": "Auto-speak Responses",
    "description": "Speak every assistant reply automatically",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "voice.aws-profile",
    "label": "AWS Profile",
    "description": "AWS credentials profile for Transcribe (blank = default chain)",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.aws-profile-2",
    "label": "AWS Profile",
    "description": "AWS credentials profile for Polly",
    "tab": "voice",
    "type": "input",
    "occurrence": 2
  },
  {
    "id": "voice.aws-region",
    "label": "AWS Region",
    "description": "AWS region for Transcribe",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.aws-region-2",
    "label": "AWS Region",
    "description": "AWS region for Polly API",
    "tab": "voice",
    "type": "input",
    "occurrence": 2
  },
  {
    "id": "voice.enabled",
    "label": "Enabled",
    "description": "Transcribe voice into the message box when you click the mic",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "voice.engine",
    "label": "Engine",
    "description": "Polly engine type",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.language",
    "label": "Language",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.microphone",
    "label": "Microphone",
    "description": "Input device used to capture your voice",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.mlx-model",
    "label": "MLX Model",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.model",
    "label": "Model",
    "description": "Larger models are more accurate but slower to run",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.piper-binary",
    "label": "Piper Binary",
    "description": "Path to the piper executable. Leave blank to auto-detect on PATH or ~/piper-venv/bin/piper",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.piper-model",
    "label": "Piper Model",
    "description": "Path to the Piper voice model (.onnx). Required — download from github.com/rhasspy/piper",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.provider",
    "label": "Provider",
    "description": "Whisper and MLX run locally; Transcribe calls AWS",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.provider-2",
    "label": "Provider",
    "description": "Piper runs locally and offline; Polly uses AWS credentials + network",
    "tab": "voice",
    "type": "select",
    "occurrence": 2
  },
  {
    "id": "voice.speed",
    "label": "Speed",
    "description": "Speech rate",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.speed-2",
    "label": "Speed",
    "description": "Piper speech speed (length scale)",
    "tab": "voice",
    "type": "select",
    "occurrence": 2
  },
  {
    "id": "voice.streaming",
    "label": "Streaming",
    "description": "Stream live partial transcripts into the input box as you speak (Transcribe only)",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "voice.voice",
    "label": "Voice",
    "description": "AWS Polly voice for TTS",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  }
]
